
package userservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import userservice.GroupAddUserRequest;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserServicePortType", targetNamespace = "http://localhost:9000/userservice.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.UserInfo
     */
    @WebMethod(operationName = "GetUserInfo", action = "http://localhost:9000/GetUserInfo")
    @WebResult(name = "UserInfo", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public UserInfo getUserInfo(
        @WebParam(name = "UserInfoRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        UserInfoRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.UserDeletionResponse
     */
    @WebMethod(operationName = "DeleteUser", action = "http://localhost:9000/DeleteUser")
    @WebResult(name = "UserDeletionResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public UserDeletionResponse deleteUser(
        @WebParam(name = "UserDeletionRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        UserDeletionRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.UserCreationResponse
     */
    @WebMethod(operationName = "CreateUser", action = "http://localhost:9000/CreateUser")
    @WebResult(name = "UserCreationResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public UserCreationResponse createUser(
        @WebParam(name = "UserCreationRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        UserCreationRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.GroupCreationResponse
     */
    @WebMethod(operationName = "CreateGroup", action = "http://localhost:9000/CreateGroup")
    @WebResult(name = "GroupCreationResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public GroupCreationResponse createGroup(
        @WebParam(name = "GroupCreationRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        GroupCreationRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.GroupDeletionResponse
     */
    @WebMethod(operationName = "DeleteGroup", action = "http://localhost:9000/DeleteGroup")
    @WebResult(name = "GroupDeletionResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public GroupDeletionResponse deleteGroup(
        @WebParam(name = "GroupDeletionRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        GroupDeletionRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.GroupAddUserResponse
     */
    @WebMethod(operationName = "GroupAddUser", action = "http://localhost:9000/GroupAddUser")
    @WebResult(name = "GroupAddUserResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public GroupAddUserResponse groupAddUser(
        @WebParam(name = "GroupAddUserRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        GroupAddUserRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.GroupDeleteUserResponse
     */
    @WebMethod(operationName = "GroupDeleteUser", action = "http://localhost:9000/GroupDeleteUser")
    @WebResult(name = "GroupDeleteUserResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public GroupDeleteUserResponse groupDeleteUser(
        @WebParam(name = "GroupDeleteUserRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        GroupDeleteUserRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns localhost._9000.userservice.GroupInfoResponse
     */
    @WebMethod(operationName = "GetGroupInfo", action = "http://localhost:9000/GetGroupInfo")
    @WebResult(name = "GroupInfoResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    public GroupInfoResponse getGroupInfo(
        @WebParam(name = "GroupInfoRequest", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
        GroupInfoRequest body);

}
