
package userservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * An example user service.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserService", targetNamespace = "http://localhost:9000/userservice.wsdl", wsdlLocation = "file:/home/sebastian/axis2-1.6.2/bin/WSDLs/userservice.wsdl")
public class UserService
    extends Service
{

    private final static URL USERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(userservice.UserService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = userservice.UserService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/sebastian/axis2-1.6.2/bin/WSDLs/userservice.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/sebastian/axis2-1.6.2/bin/WSDLs/userservice.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERSERVICE_WSDL_LOCATION = url;
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService() {
        super(USERSERVICE_WSDL_LOCATION, new QName("http://localhost:9000/userservice.wsdl", "UserService"));
    }

    /**
     * 
     * @return
     *     returns UserServicePortType
     */
    @WebEndpoint(name = "UserServicePort")
    public UserServicePortType getUserServicePort() {
        return super.getPort(new QName("http://localhost:9000/userservice.wsdl", "UserServicePort"), UserServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServicePortType
     */
    @WebEndpoint(name = "UserServicePort")
    public UserServicePortType getUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:9000/userservice.wsdl", "UserServicePort"), UserServicePortType.class, features);
    }

}
