package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-23T18:33:46.464+02:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://localhost:9000/userservice.wsdl", name = "UserServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserServicePortType {

    @WebResult(name = "GroupDeletionResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "DeleteGroup", action = "http://localhost:9000/DeleteGroup")
    public GroupDeletionResponse deleteGroup(
        @WebParam(partName = "body", name = "GroupDeletionRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        GroupDeletionRequest body
    );

    @WebResult(name = "UserCreationResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "CreateUser", action = "http://localhost:9000/CreateUser")
    public UserCreationResponse createUser(
        @WebParam(partName = "body", name = "UserCreationRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        UserCreationRequest body
    );

    @WebResult(name = "UserInfo", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "GetUserInfo", action = "http://localhost:9000/GetUserInfo")
    public UserInfo getUserInfo(
        @WebParam(partName = "body", name = "UserInfoRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        UserInfoRequest body
    );

    @WebResult(name = "GroupCreationResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "CreateGroup", action = "http://localhost:9000/CreateGroup")
    public GroupCreationResponse createGroup(
        @WebParam(partName = "body", name = "GroupCreationRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        GroupCreationRequest body
    );

    @WebResult(name = "UserDeletionResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "DeleteUser", action = "http://localhost:9000/DeleteUser")
    public UserDeletionResponse deleteUser(
        @WebParam(partName = "body", name = "UserDeletionRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        UserDeletionRequest body
    );

    @WebResult(name = "GroupInfoResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "GetGroupInfo", action = "http://localhost:9000/GetGroupInfo")
    public GroupInfoResponse getGroupInfo(
        @WebParam(partName = "body", name = "GroupInfoRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        GroupInfoRequest body
    );

    @WebResult(name = "GroupAddUserResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "GroupAddUser", action = "http://localhost:9000/GroupAddUser")
    public GroupAddUserResponse groupAddUser(
        @WebParam(partName = "body", name = "GroupAddUserRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        GroupAddUserRequest body
    );

    @WebResult(name = "GroupDeleteUserResponse", targetNamespace = "http://localhost:9000/userservice.xsd", partName = "body")
    @WebMethod(operationName = "GroupDeleteUser", action = "http://localhost:9000/GroupDeleteUser")
    public GroupDeleteUserResponse groupDeleteUser(
        @WebParam(partName = "body", name = "GroupDeleteUserRequest", targetNamespace = "http://localhost:9000/userservice.xsd")
        GroupDeleteUserRequest body
    );
}
