
package server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-23T18:33:46.517+02:00
 * Generated source version: 2.6.1
 * 
 */
 
public class UserServicePortType_UserServicePort_Server{

    protected UserServicePortType_UserServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new UserServicePortTypeImpl();
        String address = "http://0.0.0.0:9001";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new UserServicePortType_UserServicePort_Server();
        System.out.println("Server ready...");
        
        Thread.sleep(Long.MAX_VALUE);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
