/* soapUserServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.3 from ../userservice.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapUserServiceSoapBindingProxy_H
#define soapUserServiceSoapBindingProxy_H
#include "soapH.h"
class UserServiceSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'UserServiceSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	UserServiceSoapBinding()
	{ soap = soap_new(); endpoint = "http://localhost:9000/userservice"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://localhost:9000/userservice.wsdl", NULL, NULL},
	{"ns2", "http://localhost:9000/userservice.xsd", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~UserServiceSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetUserInfo' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__GetUserInfo(_ns2__UserInfoRequest *ns2__UserInfoRequest, _ns2__UserInfo *ns2__UserInfo) { return soap ? soap_call___ns1__GetUserInfo(soap, endpoint, NULL, ns2__UserInfoRequest, ns2__UserInfo) : SOAP_EOM; };
	/// Invoke 'DeleteUser' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__DeleteUser(_ns2__UserDeletionRequest *ns2__UserDeletionRequest, _ns2__UserDeletionResponse *ns2__UserDeletionResponse) { return soap ? soap_call___ns1__DeleteUser(soap, endpoint, NULL, ns2__UserDeletionRequest, ns2__UserDeletionResponse) : SOAP_EOM; };
	/// Invoke 'CreateUser' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__CreateUser(_ns2__UserCreationRequest *ns2__UserCreationRequest, _ns2__UserCreationResponse *ns2__UserCreationResponse) { return soap ? soap_call___ns1__CreateUser(soap, endpoint, NULL, ns2__UserCreationRequest, ns2__UserCreationResponse) : SOAP_EOM; };
	/// Invoke 'CreateGroup' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__CreateGroup(_ns2__GroupCreationRequest *ns2__GroupCreationRequest, _ns2__GroupCreationResponse *ns2__GroupCreationResponse) { return soap ? soap_call___ns1__CreateGroup(soap, endpoint, NULL, ns2__GroupCreationRequest, ns2__GroupCreationResponse) : SOAP_EOM; };
	/// Invoke 'DeleteGroup' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__DeleteGroup(_ns2__GroupDeletionRequest *ns2__GroupDeletionRequest, _ns2__GroupDeletionResponse *ns2__GroupDeletionResponse) { return soap ? soap_call___ns1__DeleteGroup(soap, endpoint, NULL, ns2__GroupDeletionRequest, ns2__GroupDeletionResponse) : SOAP_EOM; };
	/// Invoke 'GroupAddUser' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__GroupAddUser(_ns2__GroupAddUserRequest *ns2__GroupAddUserRequest, _ns2__GroupAddUserResponse *ns2__GroupAddUserResponse) { return soap ? soap_call___ns1__GroupAddUser(soap, endpoint, NULL, ns2__GroupAddUserRequest, ns2__GroupAddUserResponse) : SOAP_EOM; };
	/// Invoke 'GroupDeleteUser' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__GroupDeleteUser(_ns2__GroupDeleteUserRequest *ns2__GroupDeleteUserRequest, _ns2__GroupDeleteUserResponse *ns2__GroupDeleteUserResponse) { return soap ? soap_call___ns1__GroupDeleteUser(soap, endpoint, NULL, ns2__GroupDeleteUserRequest, ns2__GroupDeleteUserResponse) : SOAP_EOM; };
	/// Invoke 'GetGroupInfo' of service 'UserServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__GetGroupInfo(_ns2__GroupInfoRequest *ns2__GroupInfoRequest, _ns2__GroupInfoResponse *ns2__GroupInfoResponse) { return soap ? soap_call___ns1__GetGroupInfo(soap, endpoint, NULL, ns2__GroupInfoRequest, ns2__GroupInfoResponse) : SOAP_EOM; };
};
#endif
