/* soapH.h
   Generated by gSOAP 2.8.3 from ../userservice.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef soap_write_bool
#define soap_write_bool(soap, data) ( soap_begin_send(soap) || soap_put_bool(soap, data, "boolean", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#ifndef soap_read_bool
#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef SOAP_TYPE__ns2__GroupInfoResponse
#define SOAP_TYPE__ns2__GroupInfoResponse (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupInfoResponse(struct soap*, const char*, int, const _ns2__GroupInfoResponse *, const char*);
SOAP_FMAC3 _ns2__GroupInfoResponse * SOAP_FMAC4 soap_in__ns2__GroupInfoResponse(struct soap*, const char*, _ns2__GroupInfoResponse *, const char*);

#ifndef soap_write__ns2__GroupInfoResponse
#define soap_write__ns2__GroupInfoResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupInfoResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupInfoResponse
#define soap_read__ns2__GroupInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupInfoResponse * SOAP_FMAC4 soap_get__ns2__GroupInfoResponse(struct soap*, _ns2__GroupInfoResponse *, const char*, const char*);

#define soap_new__ns2__GroupInfoResponse(soap, n) soap_instantiate__ns2__GroupInfoResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupInfoResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupInfoResponse * SOAP_FMAC2 soap_instantiate__ns2__GroupInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupInfoRequest
#define SOAP_TYPE__ns2__GroupInfoRequest (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupInfoRequest(struct soap*, const char*, int, const _ns2__GroupInfoRequest *, const char*);
SOAP_FMAC3 _ns2__GroupInfoRequest * SOAP_FMAC4 soap_in__ns2__GroupInfoRequest(struct soap*, const char*, _ns2__GroupInfoRequest *, const char*);

#ifndef soap_write__ns2__GroupInfoRequest
#define soap_write__ns2__GroupInfoRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupInfoRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupInfoRequest
#define soap_read__ns2__GroupInfoRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupInfoRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupInfoRequest * SOAP_FMAC4 soap_get__ns2__GroupInfoRequest(struct soap*, _ns2__GroupInfoRequest *, const char*, const char*);

#define soap_new__ns2__GroupInfoRequest(soap, n) soap_instantiate__ns2__GroupInfoRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupInfoRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupInfoRequest * SOAP_FMAC2 soap_instantiate__ns2__GroupInfoRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupInfoRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupDeleteUserResponse
#define SOAP_TYPE__ns2__GroupDeleteUserResponse (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupDeleteUserResponse(struct soap*, const char*, int, const _ns2__GroupDeleteUserResponse *, const char*);
SOAP_FMAC3 _ns2__GroupDeleteUserResponse * SOAP_FMAC4 soap_in__ns2__GroupDeleteUserResponse(struct soap*, const char*, _ns2__GroupDeleteUserResponse *, const char*);

#ifndef soap_write__ns2__GroupDeleteUserResponse
#define soap_write__ns2__GroupDeleteUserResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupDeleteUserResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupDeleteUserResponse
#define soap_read__ns2__GroupDeleteUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupDeleteUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeleteUserResponse * SOAP_FMAC4 soap_get__ns2__GroupDeleteUserResponse(struct soap*, _ns2__GroupDeleteUserResponse *, const char*, const char*);

#define soap_new__ns2__GroupDeleteUserResponse(soap, n) soap_instantiate__ns2__GroupDeleteUserResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupDeleteUserResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupDeleteUserResponse * SOAP_FMAC2 soap_instantiate__ns2__GroupDeleteUserResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupDeleteUserResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupDeleteUserRequest
#define SOAP_TYPE__ns2__GroupDeleteUserRequest (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupDeleteUserRequest(struct soap*, const char*, int, const _ns2__GroupDeleteUserRequest *, const char*);
SOAP_FMAC3 _ns2__GroupDeleteUserRequest * SOAP_FMAC4 soap_in__ns2__GroupDeleteUserRequest(struct soap*, const char*, _ns2__GroupDeleteUserRequest *, const char*);

#ifndef soap_write__ns2__GroupDeleteUserRequest
#define soap_write__ns2__GroupDeleteUserRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupDeleteUserRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupDeleteUserRequest
#define soap_read__ns2__GroupDeleteUserRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupDeleteUserRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeleteUserRequest * SOAP_FMAC4 soap_get__ns2__GroupDeleteUserRequest(struct soap*, _ns2__GroupDeleteUserRequest *, const char*, const char*);

#define soap_new__ns2__GroupDeleteUserRequest(soap, n) soap_instantiate__ns2__GroupDeleteUserRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupDeleteUserRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupDeleteUserRequest * SOAP_FMAC2 soap_instantiate__ns2__GroupDeleteUserRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupDeleteUserRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupAddUserResponse
#define SOAP_TYPE__ns2__GroupAddUserResponse (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupAddUserResponse(struct soap*, const char*, int, const _ns2__GroupAddUserResponse *, const char*);
SOAP_FMAC3 _ns2__GroupAddUserResponse * SOAP_FMAC4 soap_in__ns2__GroupAddUserResponse(struct soap*, const char*, _ns2__GroupAddUserResponse *, const char*);

#ifndef soap_write__ns2__GroupAddUserResponse
#define soap_write__ns2__GroupAddUserResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupAddUserResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupAddUserResponse
#define soap_read__ns2__GroupAddUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupAddUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupAddUserResponse * SOAP_FMAC4 soap_get__ns2__GroupAddUserResponse(struct soap*, _ns2__GroupAddUserResponse *, const char*, const char*);

#define soap_new__ns2__GroupAddUserResponse(soap, n) soap_instantiate__ns2__GroupAddUserResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupAddUserResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupAddUserResponse * SOAP_FMAC2 soap_instantiate__ns2__GroupAddUserResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupAddUserResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupAddUserRequest
#define SOAP_TYPE__ns2__GroupAddUserRequest (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupAddUserRequest(struct soap*, const char*, int, const _ns2__GroupAddUserRequest *, const char*);
SOAP_FMAC3 _ns2__GroupAddUserRequest * SOAP_FMAC4 soap_in__ns2__GroupAddUserRequest(struct soap*, const char*, _ns2__GroupAddUserRequest *, const char*);

#ifndef soap_write__ns2__GroupAddUserRequest
#define soap_write__ns2__GroupAddUserRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupAddUserRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupAddUserRequest
#define soap_read__ns2__GroupAddUserRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupAddUserRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupAddUserRequest * SOAP_FMAC4 soap_get__ns2__GroupAddUserRequest(struct soap*, _ns2__GroupAddUserRequest *, const char*, const char*);

#define soap_new__ns2__GroupAddUserRequest(soap, n) soap_instantiate__ns2__GroupAddUserRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupAddUserRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupAddUserRequest * SOAP_FMAC2 soap_instantiate__ns2__GroupAddUserRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupAddUserRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupDeletionResponse
#define SOAP_TYPE__ns2__GroupDeletionResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupDeletionResponse(struct soap*, const char*, int, const _ns2__GroupDeletionResponse *, const char*);
SOAP_FMAC3 _ns2__GroupDeletionResponse * SOAP_FMAC4 soap_in__ns2__GroupDeletionResponse(struct soap*, const char*, _ns2__GroupDeletionResponse *, const char*);

#ifndef soap_write__ns2__GroupDeletionResponse
#define soap_write__ns2__GroupDeletionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupDeletionResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupDeletionResponse
#define soap_read__ns2__GroupDeletionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupDeletionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeletionResponse * SOAP_FMAC4 soap_get__ns2__GroupDeletionResponse(struct soap*, _ns2__GroupDeletionResponse *, const char*, const char*);

#define soap_new__ns2__GroupDeletionResponse(soap, n) soap_instantiate__ns2__GroupDeletionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupDeletionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupDeletionResponse * SOAP_FMAC2 soap_instantiate__ns2__GroupDeletionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupDeletionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupDeletionRequest
#define SOAP_TYPE__ns2__GroupDeletionRequest (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupDeletionRequest(struct soap*, const char*, int, const _ns2__GroupDeletionRequest *, const char*);
SOAP_FMAC3 _ns2__GroupDeletionRequest * SOAP_FMAC4 soap_in__ns2__GroupDeletionRequest(struct soap*, const char*, _ns2__GroupDeletionRequest *, const char*);

#ifndef soap_write__ns2__GroupDeletionRequest
#define soap_write__ns2__GroupDeletionRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupDeletionRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupDeletionRequest
#define soap_read__ns2__GroupDeletionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupDeletionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeletionRequest * SOAP_FMAC4 soap_get__ns2__GroupDeletionRequest(struct soap*, _ns2__GroupDeletionRequest *, const char*, const char*);

#define soap_new__ns2__GroupDeletionRequest(soap, n) soap_instantiate__ns2__GroupDeletionRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupDeletionRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupDeletionRequest * SOAP_FMAC2 soap_instantiate__ns2__GroupDeletionRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupDeletionRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupCreationResponse
#define SOAP_TYPE__ns2__GroupCreationResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupCreationResponse(struct soap*, const char*, int, const _ns2__GroupCreationResponse *, const char*);
SOAP_FMAC3 _ns2__GroupCreationResponse * SOAP_FMAC4 soap_in__ns2__GroupCreationResponse(struct soap*, const char*, _ns2__GroupCreationResponse *, const char*);

#ifndef soap_write__ns2__GroupCreationResponse
#define soap_write__ns2__GroupCreationResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupCreationResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupCreationResponse
#define soap_read__ns2__GroupCreationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupCreationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupCreationResponse * SOAP_FMAC4 soap_get__ns2__GroupCreationResponse(struct soap*, _ns2__GroupCreationResponse *, const char*, const char*);

#define soap_new__ns2__GroupCreationResponse(soap, n) soap_instantiate__ns2__GroupCreationResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupCreationResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupCreationResponse * SOAP_FMAC2 soap_instantiate__ns2__GroupCreationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupCreationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__GroupCreationRequest
#define SOAP_TYPE__ns2__GroupCreationRequest (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__GroupCreationRequest(struct soap*, const char*, int, const _ns2__GroupCreationRequest *, const char*);
SOAP_FMAC3 _ns2__GroupCreationRequest * SOAP_FMAC4 soap_in__ns2__GroupCreationRequest(struct soap*, const char*, _ns2__GroupCreationRequest *, const char*);

#ifndef soap_write__ns2__GroupCreationRequest
#define soap_write__ns2__GroupCreationRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:GroupCreationRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__GroupCreationRequest
#define soap_read__ns2__GroupCreationRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__GroupCreationRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupCreationRequest * SOAP_FMAC4 soap_get__ns2__GroupCreationRequest(struct soap*, _ns2__GroupCreationRequest *, const char*, const char*);

#define soap_new__ns2__GroupCreationRequest(soap, n) soap_instantiate__ns2__GroupCreationRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__GroupCreationRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__GroupCreationRequest * SOAP_FMAC2 soap_instantiate__ns2__GroupCreationRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__GroupCreationRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__UserCreationResponse
#define SOAP_TYPE__ns2__UserCreationResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__UserCreationResponse(struct soap*, const char*, int, const _ns2__UserCreationResponse *, const char*);
SOAP_FMAC3 _ns2__UserCreationResponse * SOAP_FMAC4 soap_in__ns2__UserCreationResponse(struct soap*, const char*, _ns2__UserCreationResponse *, const char*);

#ifndef soap_write__ns2__UserCreationResponse
#define soap_write__ns2__UserCreationResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:UserCreationResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__UserCreationResponse
#define soap_read__ns2__UserCreationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__UserCreationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserCreationResponse * SOAP_FMAC4 soap_get__ns2__UserCreationResponse(struct soap*, _ns2__UserCreationResponse *, const char*, const char*);

#define soap_new__ns2__UserCreationResponse(soap, n) soap_instantiate__ns2__UserCreationResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__UserCreationResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__UserCreationResponse * SOAP_FMAC2 soap_instantiate__ns2__UserCreationResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__UserCreationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__UserCreationRequest
#define SOAP_TYPE__ns2__UserCreationRequest (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__UserCreationRequest(struct soap*, const char*, int, const _ns2__UserCreationRequest *, const char*);
SOAP_FMAC3 _ns2__UserCreationRequest * SOAP_FMAC4 soap_in__ns2__UserCreationRequest(struct soap*, const char*, _ns2__UserCreationRequest *, const char*);

#ifndef soap_write__ns2__UserCreationRequest
#define soap_write__ns2__UserCreationRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:UserCreationRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__UserCreationRequest
#define soap_read__ns2__UserCreationRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__UserCreationRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserCreationRequest * SOAP_FMAC4 soap_get__ns2__UserCreationRequest(struct soap*, _ns2__UserCreationRequest *, const char*, const char*);

#define soap_new__ns2__UserCreationRequest(soap, n) soap_instantiate__ns2__UserCreationRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__UserCreationRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__UserCreationRequest * SOAP_FMAC2 soap_instantiate__ns2__UserCreationRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__UserCreationRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__UserDeletionResponse
#define SOAP_TYPE__ns2__UserDeletionResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__UserDeletionResponse(struct soap*, const char*, int, const _ns2__UserDeletionResponse *, const char*);
SOAP_FMAC3 _ns2__UserDeletionResponse * SOAP_FMAC4 soap_in__ns2__UserDeletionResponse(struct soap*, const char*, _ns2__UserDeletionResponse *, const char*);

#ifndef soap_write__ns2__UserDeletionResponse
#define soap_write__ns2__UserDeletionResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:UserDeletionResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__UserDeletionResponse
#define soap_read__ns2__UserDeletionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__UserDeletionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserDeletionResponse * SOAP_FMAC4 soap_get__ns2__UserDeletionResponse(struct soap*, _ns2__UserDeletionResponse *, const char*, const char*);

#define soap_new__ns2__UserDeletionResponse(soap, n) soap_instantiate__ns2__UserDeletionResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__UserDeletionResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__UserDeletionResponse * SOAP_FMAC2 soap_instantiate__ns2__UserDeletionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__UserDeletionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__UserDeletionRequest
#define SOAP_TYPE__ns2__UserDeletionRequest (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__UserDeletionRequest(struct soap*, const char*, int, const _ns2__UserDeletionRequest *, const char*);
SOAP_FMAC3 _ns2__UserDeletionRequest * SOAP_FMAC4 soap_in__ns2__UserDeletionRequest(struct soap*, const char*, _ns2__UserDeletionRequest *, const char*);

#ifndef soap_write__ns2__UserDeletionRequest
#define soap_write__ns2__UserDeletionRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:UserDeletionRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__UserDeletionRequest
#define soap_read__ns2__UserDeletionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__UserDeletionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserDeletionRequest * SOAP_FMAC4 soap_get__ns2__UserDeletionRequest(struct soap*, _ns2__UserDeletionRequest *, const char*, const char*);

#define soap_new__ns2__UserDeletionRequest(soap, n) soap_instantiate__ns2__UserDeletionRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__UserDeletionRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__UserDeletionRequest * SOAP_FMAC2 soap_instantiate__ns2__UserDeletionRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__UserDeletionRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__UserInfo
#define SOAP_TYPE__ns2__UserInfo (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__UserInfo(struct soap*, const char*, int, const _ns2__UserInfo *, const char*);
SOAP_FMAC3 _ns2__UserInfo * SOAP_FMAC4 soap_in__ns2__UserInfo(struct soap*, const char*, _ns2__UserInfo *, const char*);

#ifndef soap_write__ns2__UserInfo
#define soap_write__ns2__UserInfo(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:UserInfo", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__UserInfo
#define soap_read__ns2__UserInfo(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__UserInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserInfo * SOAP_FMAC4 soap_get__ns2__UserInfo(struct soap*, _ns2__UserInfo *, const char*, const char*);

#define soap_new__ns2__UserInfo(soap, n) soap_instantiate__ns2__UserInfo(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__UserInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__UserInfo * SOAP_FMAC2 soap_instantiate__ns2__UserInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__UserInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__UserInfoRequest
#define SOAP_TYPE__ns2__UserInfoRequest (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__UserInfoRequest(struct soap*, const char*, int, const _ns2__UserInfoRequest *, const char*);
SOAP_FMAC3 _ns2__UserInfoRequest * SOAP_FMAC4 soap_in__ns2__UserInfoRequest(struct soap*, const char*, _ns2__UserInfoRequest *, const char*);

#ifndef soap_write__ns2__UserInfoRequest
#define soap_write__ns2__UserInfoRequest(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns2:UserInfoRequest", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns2__UserInfoRequest
#define soap_read__ns2__UserInfoRequest(soap, data) ( soap_begin_recv(soap) || !soap_get__ns2__UserInfoRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserInfoRequest * SOAP_FMAC4 soap_get__ns2__UserInfoRequest(struct soap*, _ns2__UserInfoRequest *, const char*, const char*);

#define soap_new__ns2__UserInfoRequest(soap, n) soap_instantiate__ns2__UserInfoRequest(soap, n, NULL, NULL, NULL)


#define soap_delete__ns2__UserInfoRequest(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns2__UserInfoRequest * SOAP_FMAC2 soap_instantiate__ns2__UserInfoRequest(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__UserInfoRequest(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (9)
#endif

#define soap_default_xsd__integer(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__integer(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_xsd__integer
#define soap_write_xsd__integer(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:integer", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_xsd__integer
#define soap_read_xsd__integer(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__integer(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__integer(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__integer(soap, n) soap_instantiate_xsd__integer(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__integer(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__integer soap_instantiate_std__string


#define soap_copy_xsd__integer soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__GetGroupInfo
#define SOAP_TYPE___ns1__GetGroupInfo (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetGroupInfo(struct soap*, struct __ns1__GetGroupInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetGroupInfo(struct soap*, const struct __ns1__GetGroupInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetGroupInfo(struct soap*, const char*, int, const struct __ns1__GetGroupInfo *, const char*);
SOAP_FMAC3 struct __ns1__GetGroupInfo * SOAP_FMAC4 soap_in___ns1__GetGroupInfo(struct soap*, const char*, struct __ns1__GetGroupInfo *, const char*);

#ifndef soap_write___ns1__GetGroupInfo
#define soap_write___ns1__GetGroupInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetGroupInfo(soap, data), 0) || soap_put___ns1__GetGroupInfo(soap, data, "-ns1:GetGroupInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetGroupInfo(struct soap*, const struct __ns1__GetGroupInfo *, const char*, const char*);

#ifndef soap_read___ns1__GetGroupInfo
#define soap_read___ns1__GetGroupInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetGroupInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetGroupInfo * SOAP_FMAC4 soap_get___ns1__GetGroupInfo(struct soap*, struct __ns1__GetGroupInfo *, const char*, const char*);

#define soap_new___ns1__GetGroupInfo(soap, n) soap_instantiate___ns1__GetGroupInfo(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetGroupInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetGroupInfo * SOAP_FMAC2 soap_instantiate___ns1__GetGroupInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetGroupInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GroupDeleteUser
#define SOAP_TYPE___ns1__GroupDeleteUser (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GroupDeleteUser(struct soap*, struct __ns1__GroupDeleteUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GroupDeleteUser(struct soap*, const struct __ns1__GroupDeleteUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GroupDeleteUser(struct soap*, const char*, int, const struct __ns1__GroupDeleteUser *, const char*);
SOAP_FMAC3 struct __ns1__GroupDeleteUser * SOAP_FMAC4 soap_in___ns1__GroupDeleteUser(struct soap*, const char*, struct __ns1__GroupDeleteUser *, const char*);

#ifndef soap_write___ns1__GroupDeleteUser
#define soap_write___ns1__GroupDeleteUser(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GroupDeleteUser(soap, data), 0) || soap_put___ns1__GroupDeleteUser(soap, data, "-ns1:GroupDeleteUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GroupDeleteUser(struct soap*, const struct __ns1__GroupDeleteUser *, const char*, const char*);

#ifndef soap_read___ns1__GroupDeleteUser
#define soap_read___ns1__GroupDeleteUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GroupDeleteUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GroupDeleteUser * SOAP_FMAC4 soap_get___ns1__GroupDeleteUser(struct soap*, struct __ns1__GroupDeleteUser *, const char*, const char*);

#define soap_new___ns1__GroupDeleteUser(soap, n) soap_instantiate___ns1__GroupDeleteUser(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GroupDeleteUser(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GroupDeleteUser * SOAP_FMAC2 soap_instantiate___ns1__GroupDeleteUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GroupDeleteUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GroupAddUser
#define SOAP_TYPE___ns1__GroupAddUser (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GroupAddUser(struct soap*, struct __ns1__GroupAddUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GroupAddUser(struct soap*, const struct __ns1__GroupAddUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GroupAddUser(struct soap*, const char*, int, const struct __ns1__GroupAddUser *, const char*);
SOAP_FMAC3 struct __ns1__GroupAddUser * SOAP_FMAC4 soap_in___ns1__GroupAddUser(struct soap*, const char*, struct __ns1__GroupAddUser *, const char*);

#ifndef soap_write___ns1__GroupAddUser
#define soap_write___ns1__GroupAddUser(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GroupAddUser(soap, data), 0) || soap_put___ns1__GroupAddUser(soap, data, "-ns1:GroupAddUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GroupAddUser(struct soap*, const struct __ns1__GroupAddUser *, const char*, const char*);

#ifndef soap_read___ns1__GroupAddUser
#define soap_read___ns1__GroupAddUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GroupAddUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GroupAddUser * SOAP_FMAC4 soap_get___ns1__GroupAddUser(struct soap*, struct __ns1__GroupAddUser *, const char*, const char*);

#define soap_new___ns1__GroupAddUser(soap, n) soap_instantiate___ns1__GroupAddUser(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GroupAddUser(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GroupAddUser * SOAP_FMAC2 soap_instantiate___ns1__GroupAddUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GroupAddUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__DeleteGroup
#define SOAP_TYPE___ns1__DeleteGroup (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__DeleteGroup(struct soap*, struct __ns1__DeleteGroup *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__DeleteGroup(struct soap*, const struct __ns1__DeleteGroup *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__DeleteGroup(struct soap*, const char*, int, const struct __ns1__DeleteGroup *, const char*);
SOAP_FMAC3 struct __ns1__DeleteGroup * SOAP_FMAC4 soap_in___ns1__DeleteGroup(struct soap*, const char*, struct __ns1__DeleteGroup *, const char*);

#ifndef soap_write___ns1__DeleteGroup
#define soap_write___ns1__DeleteGroup(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__DeleteGroup(soap, data), 0) || soap_put___ns1__DeleteGroup(soap, data, "-ns1:DeleteGroup", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__DeleteGroup(struct soap*, const struct __ns1__DeleteGroup *, const char*, const char*);

#ifndef soap_read___ns1__DeleteGroup
#define soap_read___ns1__DeleteGroup(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__DeleteGroup(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__DeleteGroup * SOAP_FMAC4 soap_get___ns1__DeleteGroup(struct soap*, struct __ns1__DeleteGroup *, const char*, const char*);

#define soap_new___ns1__DeleteGroup(soap, n) soap_instantiate___ns1__DeleteGroup(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__DeleteGroup(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__DeleteGroup * SOAP_FMAC2 soap_instantiate___ns1__DeleteGroup(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__DeleteGroup(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__CreateGroup
#define SOAP_TYPE___ns1__CreateGroup (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__CreateGroup(struct soap*, struct __ns1__CreateGroup *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__CreateGroup(struct soap*, const struct __ns1__CreateGroup *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__CreateGroup(struct soap*, const char*, int, const struct __ns1__CreateGroup *, const char*);
SOAP_FMAC3 struct __ns1__CreateGroup * SOAP_FMAC4 soap_in___ns1__CreateGroup(struct soap*, const char*, struct __ns1__CreateGroup *, const char*);

#ifndef soap_write___ns1__CreateGroup
#define soap_write___ns1__CreateGroup(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__CreateGroup(soap, data), 0) || soap_put___ns1__CreateGroup(soap, data, "-ns1:CreateGroup", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__CreateGroup(struct soap*, const struct __ns1__CreateGroup *, const char*, const char*);

#ifndef soap_read___ns1__CreateGroup
#define soap_read___ns1__CreateGroup(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__CreateGroup(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__CreateGroup * SOAP_FMAC4 soap_get___ns1__CreateGroup(struct soap*, struct __ns1__CreateGroup *, const char*, const char*);

#define soap_new___ns1__CreateGroup(soap, n) soap_instantiate___ns1__CreateGroup(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__CreateGroup(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__CreateGroup * SOAP_FMAC2 soap_instantiate___ns1__CreateGroup(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__CreateGroup(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__CreateUser
#define SOAP_TYPE___ns1__CreateUser (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__CreateUser(struct soap*, struct __ns1__CreateUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__CreateUser(struct soap*, const struct __ns1__CreateUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__CreateUser(struct soap*, const char*, int, const struct __ns1__CreateUser *, const char*);
SOAP_FMAC3 struct __ns1__CreateUser * SOAP_FMAC4 soap_in___ns1__CreateUser(struct soap*, const char*, struct __ns1__CreateUser *, const char*);

#ifndef soap_write___ns1__CreateUser
#define soap_write___ns1__CreateUser(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__CreateUser(soap, data), 0) || soap_put___ns1__CreateUser(soap, data, "-ns1:CreateUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__CreateUser(struct soap*, const struct __ns1__CreateUser *, const char*, const char*);

#ifndef soap_read___ns1__CreateUser
#define soap_read___ns1__CreateUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__CreateUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__CreateUser * SOAP_FMAC4 soap_get___ns1__CreateUser(struct soap*, struct __ns1__CreateUser *, const char*, const char*);

#define soap_new___ns1__CreateUser(soap, n) soap_instantiate___ns1__CreateUser(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__CreateUser(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__CreateUser * SOAP_FMAC2 soap_instantiate___ns1__CreateUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__CreateUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__DeleteUser
#define SOAP_TYPE___ns1__DeleteUser (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__DeleteUser(struct soap*, struct __ns1__DeleteUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__DeleteUser(struct soap*, const struct __ns1__DeleteUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__DeleteUser(struct soap*, const char*, int, const struct __ns1__DeleteUser *, const char*);
SOAP_FMAC3 struct __ns1__DeleteUser * SOAP_FMAC4 soap_in___ns1__DeleteUser(struct soap*, const char*, struct __ns1__DeleteUser *, const char*);

#ifndef soap_write___ns1__DeleteUser
#define soap_write___ns1__DeleteUser(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__DeleteUser(soap, data), 0) || soap_put___ns1__DeleteUser(soap, data, "-ns1:DeleteUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__DeleteUser(struct soap*, const struct __ns1__DeleteUser *, const char*, const char*);

#ifndef soap_read___ns1__DeleteUser
#define soap_read___ns1__DeleteUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__DeleteUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__DeleteUser * SOAP_FMAC4 soap_get___ns1__DeleteUser(struct soap*, struct __ns1__DeleteUser *, const char*, const char*);

#define soap_new___ns1__DeleteUser(soap, n) soap_instantiate___ns1__DeleteUser(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__DeleteUser(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__DeleteUser * SOAP_FMAC2 soap_instantiate___ns1__DeleteUser(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__DeleteUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetUserInfo
#define SOAP_TYPE___ns1__GetUserInfo (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetUserInfo(struct soap*, struct __ns1__GetUserInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetUserInfo(struct soap*, const struct __ns1__GetUserInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetUserInfo(struct soap*, const char*, int, const struct __ns1__GetUserInfo *, const char*);
SOAP_FMAC3 struct __ns1__GetUserInfo * SOAP_FMAC4 soap_in___ns1__GetUserInfo(struct soap*, const char*, struct __ns1__GetUserInfo *, const char*);

#ifndef soap_write___ns1__GetUserInfo
#define soap_write___ns1__GetUserInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetUserInfo(soap, data), 0) || soap_put___ns1__GetUserInfo(soap, data, "-ns1:GetUserInfo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetUserInfo(struct soap*, const struct __ns1__GetUserInfo *, const char*, const char*);

#ifndef soap_read___ns1__GetUserInfo
#define soap_read___ns1__GetUserInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetUserInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetUserInfo * SOAP_FMAC4 soap_get___ns1__GetUserInfo(struct soap*, struct __ns1__GetUserInfo *, const char*, const char*);

#define soap_new___ns1__GetUserInfo(soap, n) soap_instantiate___ns1__GetUserInfo(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetUserInfo(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetUserInfo * SOAP_FMAC2 soap_instantiate___ns1__GetUserInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetUserInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns2__GroupInfoResponse
#define SOAP_TYPE_PointerTo_ns2__GroupInfoResponse (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupInfoResponse(struct soap*, _ns2__GroupInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupInfoResponse(struct soap*, const char *, int, _ns2__GroupInfoResponse *const*, const char *);
SOAP_FMAC3 _ns2__GroupInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupInfoResponse(struct soap*, const char*, _ns2__GroupInfoResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupInfoResponse
#define soap_write_PointerTo_ns2__GroupInfoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupInfoResponse(soap, data), 0) || soap_put_PointerTo_ns2__GroupInfoResponse(soap, data, "ns2:GroupInfoResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupInfoResponse(struct soap*, _ns2__GroupInfoResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupInfoResponse
#define soap_read_PointerTo_ns2__GroupInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupInfoResponse(struct soap*, _ns2__GroupInfoResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupInfoRequest
#define SOAP_TYPE_PointerTo_ns2__GroupInfoRequest (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupInfoRequest(struct soap*, _ns2__GroupInfoRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupInfoRequest(struct soap*, const char *, int, _ns2__GroupInfoRequest *const*, const char *);
SOAP_FMAC3 _ns2__GroupInfoRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupInfoRequest(struct soap*, const char*, _ns2__GroupInfoRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupInfoRequest
#define soap_write_PointerTo_ns2__GroupInfoRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupInfoRequest(soap, data), 0) || soap_put_PointerTo_ns2__GroupInfoRequest(soap, data, "ns2:GroupInfoRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupInfoRequest(struct soap*, _ns2__GroupInfoRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupInfoRequest
#define soap_read_PointerTo_ns2__GroupInfoRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupInfoRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupInfoRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupInfoRequest(struct soap*, _ns2__GroupInfoRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupDeleteUserResponse
#define SOAP_TYPE_PointerTo_ns2__GroupDeleteUserResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupDeleteUserResponse(struct soap*, _ns2__GroupDeleteUserResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupDeleteUserResponse(struct soap*, const char *, int, _ns2__GroupDeleteUserResponse *const*, const char *);
SOAP_FMAC3 _ns2__GroupDeleteUserResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupDeleteUserResponse(struct soap*, const char*, _ns2__GroupDeleteUserResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupDeleteUserResponse
#define soap_write_PointerTo_ns2__GroupDeleteUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupDeleteUserResponse(soap, data), 0) || soap_put_PointerTo_ns2__GroupDeleteUserResponse(soap, data, "ns2:GroupDeleteUserResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupDeleteUserResponse(struct soap*, _ns2__GroupDeleteUserResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupDeleteUserResponse
#define soap_read_PointerTo_ns2__GroupDeleteUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupDeleteUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeleteUserResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupDeleteUserResponse(struct soap*, _ns2__GroupDeleteUserResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupDeleteUserRequest
#define SOAP_TYPE_PointerTo_ns2__GroupDeleteUserRequest (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupDeleteUserRequest(struct soap*, _ns2__GroupDeleteUserRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupDeleteUserRequest(struct soap*, const char *, int, _ns2__GroupDeleteUserRequest *const*, const char *);
SOAP_FMAC3 _ns2__GroupDeleteUserRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupDeleteUserRequest(struct soap*, const char*, _ns2__GroupDeleteUserRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupDeleteUserRequest
#define soap_write_PointerTo_ns2__GroupDeleteUserRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupDeleteUserRequest(soap, data), 0) || soap_put_PointerTo_ns2__GroupDeleteUserRequest(soap, data, "ns2:GroupDeleteUserRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupDeleteUserRequest(struct soap*, _ns2__GroupDeleteUserRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupDeleteUserRequest
#define soap_read_PointerTo_ns2__GroupDeleteUserRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupDeleteUserRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeleteUserRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupDeleteUserRequest(struct soap*, _ns2__GroupDeleteUserRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupAddUserResponse
#define SOAP_TYPE_PointerTo_ns2__GroupAddUserResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupAddUserResponse(struct soap*, _ns2__GroupAddUserResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupAddUserResponse(struct soap*, const char *, int, _ns2__GroupAddUserResponse *const*, const char *);
SOAP_FMAC3 _ns2__GroupAddUserResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupAddUserResponse(struct soap*, const char*, _ns2__GroupAddUserResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupAddUserResponse
#define soap_write_PointerTo_ns2__GroupAddUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupAddUserResponse(soap, data), 0) || soap_put_PointerTo_ns2__GroupAddUserResponse(soap, data, "ns2:GroupAddUserResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupAddUserResponse(struct soap*, _ns2__GroupAddUserResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupAddUserResponse
#define soap_read_PointerTo_ns2__GroupAddUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupAddUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupAddUserResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupAddUserResponse(struct soap*, _ns2__GroupAddUserResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupAddUserRequest
#define SOAP_TYPE_PointerTo_ns2__GroupAddUserRequest (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupAddUserRequest(struct soap*, _ns2__GroupAddUserRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupAddUserRequest(struct soap*, const char *, int, _ns2__GroupAddUserRequest *const*, const char *);
SOAP_FMAC3 _ns2__GroupAddUserRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupAddUserRequest(struct soap*, const char*, _ns2__GroupAddUserRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupAddUserRequest
#define soap_write_PointerTo_ns2__GroupAddUserRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupAddUserRequest(soap, data), 0) || soap_put_PointerTo_ns2__GroupAddUserRequest(soap, data, "ns2:GroupAddUserRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupAddUserRequest(struct soap*, _ns2__GroupAddUserRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupAddUserRequest
#define soap_read_PointerTo_ns2__GroupAddUserRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupAddUserRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupAddUserRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupAddUserRequest(struct soap*, _ns2__GroupAddUserRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupDeletionResponse
#define SOAP_TYPE_PointerTo_ns2__GroupDeletionResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupDeletionResponse(struct soap*, _ns2__GroupDeletionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupDeletionResponse(struct soap*, const char *, int, _ns2__GroupDeletionResponse *const*, const char *);
SOAP_FMAC3 _ns2__GroupDeletionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupDeletionResponse(struct soap*, const char*, _ns2__GroupDeletionResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupDeletionResponse
#define soap_write_PointerTo_ns2__GroupDeletionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupDeletionResponse(soap, data), 0) || soap_put_PointerTo_ns2__GroupDeletionResponse(soap, data, "ns2:GroupDeletionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupDeletionResponse(struct soap*, _ns2__GroupDeletionResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupDeletionResponse
#define soap_read_PointerTo_ns2__GroupDeletionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupDeletionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeletionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupDeletionResponse(struct soap*, _ns2__GroupDeletionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupDeletionRequest
#define SOAP_TYPE_PointerTo_ns2__GroupDeletionRequest (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupDeletionRequest(struct soap*, _ns2__GroupDeletionRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupDeletionRequest(struct soap*, const char *, int, _ns2__GroupDeletionRequest *const*, const char *);
SOAP_FMAC3 _ns2__GroupDeletionRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupDeletionRequest(struct soap*, const char*, _ns2__GroupDeletionRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupDeletionRequest
#define soap_write_PointerTo_ns2__GroupDeletionRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupDeletionRequest(soap, data), 0) || soap_put_PointerTo_ns2__GroupDeletionRequest(soap, data, "ns2:GroupDeletionRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupDeletionRequest(struct soap*, _ns2__GroupDeletionRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupDeletionRequest
#define soap_read_PointerTo_ns2__GroupDeletionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupDeletionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupDeletionRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupDeletionRequest(struct soap*, _ns2__GroupDeletionRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupCreationResponse
#define SOAP_TYPE_PointerTo_ns2__GroupCreationResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupCreationResponse(struct soap*, _ns2__GroupCreationResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupCreationResponse(struct soap*, const char *, int, _ns2__GroupCreationResponse *const*, const char *);
SOAP_FMAC3 _ns2__GroupCreationResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupCreationResponse(struct soap*, const char*, _ns2__GroupCreationResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupCreationResponse
#define soap_write_PointerTo_ns2__GroupCreationResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupCreationResponse(soap, data), 0) || soap_put_PointerTo_ns2__GroupCreationResponse(soap, data, "ns2:GroupCreationResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupCreationResponse(struct soap*, _ns2__GroupCreationResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupCreationResponse
#define soap_read_PointerTo_ns2__GroupCreationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupCreationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupCreationResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupCreationResponse(struct soap*, _ns2__GroupCreationResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__GroupCreationRequest
#define SOAP_TYPE_PointerTo_ns2__GroupCreationRequest (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__GroupCreationRequest(struct soap*, _ns2__GroupCreationRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__GroupCreationRequest(struct soap*, const char *, int, _ns2__GroupCreationRequest *const*, const char *);
SOAP_FMAC3 _ns2__GroupCreationRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__GroupCreationRequest(struct soap*, const char*, _ns2__GroupCreationRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__GroupCreationRequest
#define soap_write_PointerTo_ns2__GroupCreationRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__GroupCreationRequest(soap, data), 0) || soap_put_PointerTo_ns2__GroupCreationRequest(soap, data, "ns2:GroupCreationRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__GroupCreationRequest(struct soap*, _ns2__GroupCreationRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__GroupCreationRequest
#define soap_read_PointerTo_ns2__GroupCreationRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__GroupCreationRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__GroupCreationRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__GroupCreationRequest(struct soap*, _ns2__GroupCreationRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__UserCreationResponse
#define SOAP_TYPE_PointerTo_ns2__UserCreationResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__UserCreationResponse(struct soap*, _ns2__UserCreationResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__UserCreationResponse(struct soap*, const char *, int, _ns2__UserCreationResponse *const*, const char *);
SOAP_FMAC3 _ns2__UserCreationResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__UserCreationResponse(struct soap*, const char*, _ns2__UserCreationResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__UserCreationResponse
#define soap_write_PointerTo_ns2__UserCreationResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__UserCreationResponse(soap, data), 0) || soap_put_PointerTo_ns2__UserCreationResponse(soap, data, "ns2:UserCreationResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__UserCreationResponse(struct soap*, _ns2__UserCreationResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__UserCreationResponse
#define soap_read_PointerTo_ns2__UserCreationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__UserCreationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserCreationResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__UserCreationResponse(struct soap*, _ns2__UserCreationResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__UserCreationRequest
#define SOAP_TYPE_PointerTo_ns2__UserCreationRequest (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__UserCreationRequest(struct soap*, _ns2__UserCreationRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__UserCreationRequest(struct soap*, const char *, int, _ns2__UserCreationRequest *const*, const char *);
SOAP_FMAC3 _ns2__UserCreationRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__UserCreationRequest(struct soap*, const char*, _ns2__UserCreationRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__UserCreationRequest
#define soap_write_PointerTo_ns2__UserCreationRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__UserCreationRequest(soap, data), 0) || soap_put_PointerTo_ns2__UserCreationRequest(soap, data, "ns2:UserCreationRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__UserCreationRequest(struct soap*, _ns2__UserCreationRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__UserCreationRequest
#define soap_read_PointerTo_ns2__UserCreationRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__UserCreationRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserCreationRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__UserCreationRequest(struct soap*, _ns2__UserCreationRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__UserDeletionResponse
#define SOAP_TYPE_PointerTo_ns2__UserDeletionResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__UserDeletionResponse(struct soap*, _ns2__UserDeletionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__UserDeletionResponse(struct soap*, const char *, int, _ns2__UserDeletionResponse *const*, const char *);
SOAP_FMAC3 _ns2__UserDeletionResponse ** SOAP_FMAC4 soap_in_PointerTo_ns2__UserDeletionResponse(struct soap*, const char*, _ns2__UserDeletionResponse **, const char*);

#ifndef soap_write_PointerTo_ns2__UserDeletionResponse
#define soap_write_PointerTo_ns2__UserDeletionResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__UserDeletionResponse(soap, data), 0) || soap_put_PointerTo_ns2__UserDeletionResponse(soap, data, "ns2:UserDeletionResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__UserDeletionResponse(struct soap*, _ns2__UserDeletionResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__UserDeletionResponse
#define soap_read_PointerTo_ns2__UserDeletionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__UserDeletionResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserDeletionResponse ** SOAP_FMAC4 soap_get_PointerTo_ns2__UserDeletionResponse(struct soap*, _ns2__UserDeletionResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__UserDeletionRequest
#define SOAP_TYPE_PointerTo_ns2__UserDeletionRequest (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__UserDeletionRequest(struct soap*, _ns2__UserDeletionRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__UserDeletionRequest(struct soap*, const char *, int, _ns2__UserDeletionRequest *const*, const char *);
SOAP_FMAC3 _ns2__UserDeletionRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__UserDeletionRequest(struct soap*, const char*, _ns2__UserDeletionRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__UserDeletionRequest
#define soap_write_PointerTo_ns2__UserDeletionRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__UserDeletionRequest(soap, data), 0) || soap_put_PointerTo_ns2__UserDeletionRequest(soap, data, "ns2:UserDeletionRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__UserDeletionRequest(struct soap*, _ns2__UserDeletionRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__UserDeletionRequest
#define soap_read_PointerTo_ns2__UserDeletionRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__UserDeletionRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserDeletionRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__UserDeletionRequest(struct soap*, _ns2__UserDeletionRequest **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__UserInfo
#define SOAP_TYPE_PointerTo_ns2__UserInfo (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__UserInfo(struct soap*, _ns2__UserInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__UserInfo(struct soap*, const char *, int, _ns2__UserInfo *const*, const char *);
SOAP_FMAC3 _ns2__UserInfo ** SOAP_FMAC4 soap_in_PointerTo_ns2__UserInfo(struct soap*, const char*, _ns2__UserInfo **, const char*);

#ifndef soap_write_PointerTo_ns2__UserInfo
#define soap_write_PointerTo_ns2__UserInfo(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__UserInfo(soap, data), 0) || soap_put_PointerTo_ns2__UserInfo(soap, data, "ns2:UserInfo", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__UserInfo(struct soap*, _ns2__UserInfo *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__UserInfo
#define soap_read_PointerTo_ns2__UserInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__UserInfo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserInfo ** SOAP_FMAC4 soap_get_PointerTo_ns2__UserInfo(struct soap*, _ns2__UserInfo **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__UserInfoRequest
#define SOAP_TYPE_PointerTo_ns2__UserInfoRequest (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__UserInfoRequest(struct soap*, _ns2__UserInfoRequest *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__UserInfoRequest(struct soap*, const char *, int, _ns2__UserInfoRequest *const*, const char *);
SOAP_FMAC3 _ns2__UserInfoRequest ** SOAP_FMAC4 soap_in_PointerTo_ns2__UserInfoRequest(struct soap*, const char*, _ns2__UserInfoRequest **, const char*);

#ifndef soap_write_PointerTo_ns2__UserInfoRequest
#define soap_write_PointerTo_ns2__UserInfoRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns2__UserInfoRequest(soap, data), 0) || soap_put_PointerTo_ns2__UserInfoRequest(soap, data, "ns2:UserInfoRequest", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__UserInfoRequest(struct soap*, _ns2__UserInfoRequest *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns2__UserInfoRequest
#define soap_read_PointerTo_ns2__UserInfoRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns2__UserInfoRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns2__UserInfoRequest ** SOAP_FMAC4 soap_get_PointerTo_ns2__UserInfoRequest(struct soap*, _ns2__UserInfoRequest **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfstd__string
#define SOAP_TYPE_std__vectorTemplateOfstd__string (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfstd__string(struct soap*, std::vector<std::string >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfstd__string(struct soap*, const std::vector<std::string >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfstd__string(struct soap*, const char*, int, const std::vector<std::string >*, const char*);
SOAP_FMAC3 std::vector<std::string >* SOAP_FMAC4 soap_in_std__vectorTemplateOfstd__string(struct soap*, const char*, std::vector<std::string >*, const char*);

#define soap_new_std__vectorTemplateOfstd__string(soap, n) soap_instantiate_std__vectorTemplateOfstd__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfstd__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<std::string > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfstd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfstd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
